// constants.js
const TRY_BEFORE_YOU_BUY = 'TRY_BEFORE_YOU_BUY';
const PERCENTAGE = "PERCENTAGE";
const NO_REMAINING_BALANCE = "NO_REMAINING_BALANCE";
const TIME_AFTER_CHECKOUT = "TIME_AFTER_CHECKOUT";

module.exports = {
  TRY_BEFORE_YOU_BUY,
  PERCENTAGE,
  NO_REMAINING_BALANCE,
  TIME_AFTER_CHECKOUT
};
